version: '3'

services:
  postgres:
    container_name: db
    image: postgres:14.7
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - main

  web:
    container_name: blog
    build: .
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn -w 5 --bind 0.0.0.0:8001 myblog.wsgi "
    depends_on:
      - postgres
    networks:
      - main
    volumes:
      - .:/opt/app


  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - main
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./static/:/opt/app/static
      - ./media/:/opt/app//media

  certbot:
    image: certbot/certbot:latest
    command: bash -c "certbot certonly --webroot --webroot-path /var/www/certbot/ -d freports.space"
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

volumes:
  pg-data:

