version: '3'

services:
  postgres:
    container_name: db
    image: postgres:14.7
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - main

  web:
    container_name: blog
    build: .
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001 "
    depends_on:
      - postgres
    ports:
      - "8001:8001"
    networks:
      - main
    volumes:
      - .:/opt/app


volumes:
  pg-data:
  static:


networks:
  main:

