version: '3'

services:
  postgres:
    container_name: db
    image: postgres:14.7
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: 'myapi'
      POSTGRES_USER: 'benya'
      POSTGRES_PASSWORD: '1111'
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - main

  django:
    container_name: blog
    build: .
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn myblog.wsgi --bind 0.0.0.0:8001"

    expose:
      - 8001
    depends_on:
      - postgres
    networks:
      - main
    volumes:
      - .:/opt/app

  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - django
    ports:
      - "80:80"
    networks:
      - main
    volumes:
      - ./nginx/:/etc/nginx/conf.d/


volumes:
  pg-data:

networks:
  main:
